# Generated by Django 5.2.7 on 2025-12-19

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q, F
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("draft", "Черновик"), ("in_progress", "В работе"), ("completed", "Завершён"), ("cancelled", "Отменён")], db_index=True, default="draft", max_length=16)),
                ("budget_final", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_as_customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_as_freelancer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "freelancer"], name="order_status_freel_idx"),
                    models.Index(fields=["status", "customer"], name="order_status_cust_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.PositiveSmallIntegerField()),
                ("text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_written",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="projects.order",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "author")},
                "indexes": [
                    models.Index(fields=["target", "created_at"], name="review_target_created_idx"),
                    models.Index(fields=["order"], name="review_order_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(check=models.Q(("rating__gte", 1), ("rating__lte", 5)), name="review_rating_1_5")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(check=~Q(customer=F("freelancer")), name="order_customer_ne_freelancer"),
        ),
    ]
