# Generated by Django 5.2.7 on 2025-10-17 16:27

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='skill_name_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxonomy.category')),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='taxonomy_ca_slug_79d2b3_idx'), models.Index(fields=['parent'], name='taxonomy_ca_parent__1d5774_idx')],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Junior'), (2, 'Middle'), (3, 'Senior'), (4, 'Expert')], default=1)),
                ('years', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_users', to='taxonomy.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='taxonomy_us_user_id_32da55_idx'), models.Index(fields=['skill'], name='taxonomy_us_skill_i_77499b_idx')],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
