# Generated by Django 5.2.7 on 2025-12-21 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_category'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.ForeignKey(blank=True, help_text='????????????? ????????????', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='taxonomy.category'),
        ),
    ]
